---
- hosts: webserver
  become: True
  tasks:
    - name: Install HTTPD
      yum: 
        name: "httpd" 
        state: "present"
    - name: Start Apache server   
      service: 
        name: httpd 
        state: started
        enabled: True
    - name: Deploy static web content
      copy:
        src: index.html
        dest: /var/www/html

